<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-02 23:31
=======
# Generated by Django 3.1.2 on 2020-11-02 22:52
>>>>>>> origin/master

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201030_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
<<<<<<< HEAD
            field=models.CharField(default='', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
=======
            field=models.CharField(default='defaultuser', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
>>>>>>> origin/master
            preserve_default=False,
        ),
    ]
